name: sgidt_mobile
description: "AplicaciÃ³n mÃ³vil de SGIDT."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  shared_preferences: ^2.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6   # ğŸ‘ˆ se deja aquÃ­ (solo se usa en build)

flutter:
  uses-material-design: true

  # ğŸ“¦ Archivos incluidos (logo para splash)
  assets:
    - assets/logo.png

# âš™ï¸ ConfiguraciÃ³n de splash nativo
flutter_native_splash:
  color: "#FFFFFF"            # Fondo claro
  color_dark: "#232323"       # Fondo oscuro
  # Ajustes para Android 12+
  android_12:
    color: "#FFFFFF"
    color_dark: "#232323"
